//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CldvPoePartOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Transaction_ID { get; set; }
        public int User_ID { get; set; }
        public int Product_ID { get; set; }
        public int Quantity { get; set; }
        public double Product_Price { get; set; }
        public Nullable<System.DateTime> Transaction_date { get; set; }
        public string Product_Name { get; set; }
        public string Author { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
